import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import ProductCard from '@/components/ProductCard'
import { useEffect, useState } from 'react'
import GroupLoadingSkeleton from '@/components/LoadingSkeleton'
import { getProduct, getProducts } from '@/services/api'
import { useCategory } from '@/contexts/CategoryContext'
import { CategoryType } from '@/types/enum'

export default function Home() {
  const [products, setProducts] = useState<Product[]>([])
  const [isLoading, setLoading] = useState(false)
  const { category } = useCategory()

  useEffect(() => {
    setLoading(true)
    setTimeout(() => getProducts()
    .then(data => {
      let filtered = data
      if (category !== "") {
        filtered = data.filter(d => {console.log(d.category); return d.category === CategoryType[category as keyof typeof CategoryType]})
      }
      setProducts(filtered)
      setLoading(false)
    }), 1500)
  }, [category])
  
  if (isLoading) return <GroupLoadingSkeleton />

  return (
    <>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>

      </div>
      <div className="p-14 background">
        <div className="grid grid-cols-4 gap-4 justify-items-center">
          {products.map(p => <ProductCard key={p.name} imgUrl={p.image} name={p.name} price={p.price} />)}
        </div>
      </div>
    </>
  )
}