import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import ProductCard from '@/components/ProductCard'
import { useEffect, useState } from 'react'
import GroupLoadingSkeleton from '@/components/LoadingSkeleton'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [products, setProducts] = useState<Product[]>([])
  const [isLoading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true)
    setTimeout(() => fetch("/api/products")
    .then(res => res.json())
    .then(data => {
      setProducts(data.products)
      setLoading(false)
    }), 3000)
    
  }, [])
  
  if (isLoading) return <GroupLoadingSkeleton />

  return (
    <>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>

      </div>
      <div className="p-14 background">
        <div className="grid grid-cols-4 gap-4 justify-items-center">
          {products.map(p => <ProductCard key={p.name} imgUrl={p.image} name={p.name} price={p.price} />)}
        </div>
      </div>
    </>
  )
}